package br.unibh.sdm.backend_estacionamento.entidades;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "estacionamento")
public class Estacionamento {
    private String nome;
    private String localizacao;
    private List<VagaEstacionamento> vagas;

    public Estacionamento(String nome, String localizacao) {
        this.nome = nome;
        this.localizacao = localizacao;
        this.vagas = new ArrayList<>();
    }
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public void adicionarVaga(VagaEstacionamento vaga) {
        vagas.add(vaga);
    }

    public void removerVaga(VagaEstacionamento vaga) {
        vagas.remove(vaga);
    }

    public List<VagaEstacionamento> verificarVagasDisponiveis() {
        List<VagaEstacionamento> vagasDisponiveis = new ArrayList<>();
        for (VagaEstacionamento vaga : vagas) {
            if (!vaga.isDisponivel()) {
                vagasDisponiveis.add(vaga);
            }
        }
        return vagasDisponiveis;
    }

    @DynamoDBAttribute
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @DynamoDBAttribute
    public String getLocalizacao() {
        return localizacao;
    }

    public void setLocalizacao(String localizacao) {
        this.localizacao = localizacao;
    }

    @DynamoDBAttribute
    public List<VagaEstacionamento> getVagas() {
        return vagas;
    }

    public void setVagas(List<VagaEstacionamento> vagas) {
        this.vagas = vagas;
    }
}
